(load "interpreter.scm")

; General testing framework
(define test
  (lambda (filename expected-output)
    (if (eq? (car (interpret filename)) expected-output)
        (string-append "Passed " filename)
        (string-append "Failed " filename)

; Tests 1
(test "Tests/test1.java" 150)
(test "Tests/test2.java" -4)
(test "Tests/test3.java" 10)
(test "Tests/test4.java" 16)
(test "Tests/test5.java" 220)
(test "Tests/test6.java" 5)
(test "Tests/test7.java" 6)
(test "Tests/test8.java" 10)
(test "Tests/test9.java" 5)
(test "Tests/test10.java" -39)
(test "Tests/test11.java" `error)
(test "Tests/test12.java" `error)
(test "Tests/test13.java" `error)
(test "Tests/test14.java" `error)
(test "Tests/test15.java" `true)
(test "Tests/test16.java" 100)
(test "Tests/test17.java" `false)
(test "Tests/test18.java" true)
(test "Tests/test19.java" 128)
(test "Tests/test20.java" 12)
(test "Tests/test21.java" 30)
(test "Tests/test22.java" 11)
(test "Tests/test23.java" 1106)
(test "Tests/test24.java" 12)
(test "Tests/test25.java" 16)
(test "Tests/test26.java" 72)
(test "Tests/test27.java" 21)
(test "Tests/test28.java" 164)
